// AUTOGENERATED by packages/coding-agent/scripts/generate-prompt-variants.ts
// Do not edit by hand. Re-run the generator to refresh.
//
// Source baseline: gentle commit text (current source files).
// Pre-gentle baseline: commit 3f073b82d.
// Caveman baseline: hand-authored in _variants/caveman/.

import { registerPromptVariants } from "@oh-my-pi/pi-utils/prompt";
import gentle_compactionPromptsBranchSummaryMd from "./compaction/prompts/branch-summary.md" with { type: "text" };
import default_compactionPromptsBranchSummaryMd from "./_variants/default/compaction/prompts/branch-summary.md" with { type: "text" };
import caveman_compactionPromptsBranchSummaryMd from "./_variants/caveman/compaction/prompts/branch-summary.md" with { type: "text" };
import gentle_compactionPromptsCompactionShortSummaryMd from "./compaction/prompts/compaction-short-summary.md" with { type: "text" };
import default_compactionPromptsCompactionShortSummaryMd from "./_variants/default/compaction/prompts/compaction-short-summary.md" with { type: "text" };
import caveman_compactionPromptsCompactionShortSummaryMd from "./_variants/caveman/compaction/prompts/compaction-short-summary.md" with { type: "text" };
import gentle_compactionPromptsCompactionSummaryContextMd from "./compaction/prompts/compaction-summary-context.md" with { type: "text" };
import default_compactionPromptsCompactionSummaryContextMd from "./_variants/default/compaction/prompts/compaction-summary-context.md" with { type: "text" };
import caveman_compactionPromptsCompactionSummaryContextMd from "./_variants/caveman/compaction/prompts/compaction-summary-context.md" with { type: "text" };
import gentle_compactionPromptsCompactionSummaryMd from "./compaction/prompts/compaction-summary.md" with { type: "text" };
import default_compactionPromptsCompactionSummaryMd from "./_variants/default/compaction/prompts/compaction-summary.md" with { type: "text" };
import caveman_compactionPromptsCompactionSummaryMd from "./_variants/caveman/compaction/prompts/compaction-summary.md" with { type: "text" };
import gentle_compactionPromptsCompactionTurnPrefixMd from "./compaction/prompts/compaction-turn-prefix.md" with { type: "text" };
import default_compactionPromptsCompactionTurnPrefixMd from "./_variants/default/compaction/prompts/compaction-turn-prefix.md" with { type: "text" };
import caveman_compactionPromptsCompactionTurnPrefixMd from "./_variants/caveman/compaction/prompts/compaction-turn-prefix.md" with { type: "text" };
import gentle_compactionPromptsCompactionUpdateSummaryMd from "./compaction/prompts/compaction-update-summary.md" with { type: "text" };
import default_compactionPromptsCompactionUpdateSummaryMd from "./_variants/default/compaction/prompts/compaction-update-summary.md" with { type: "text" };
import caveman_compactionPromptsCompactionUpdateSummaryMd from "./_variants/caveman/compaction/prompts/compaction-update-summary.md" with { type: "text" };
import gentle_compactionPromptsHandoffDocumentMd from "./compaction/prompts/handoff-document.md" with { type: "text" };
import default_compactionPromptsHandoffDocumentMd from "./_variants/default/compaction/prompts/handoff-document.md" with { type: "text" };
import caveman_compactionPromptsHandoffDocumentMd from "./_variants/caveman/compaction/prompts/handoff-document.md" with { type: "text" };
import gentle_compactionPromptsSummarizationSystemMd from "./compaction/prompts/summarization-system.md" with { type: "text" };
import default_compactionPromptsSummarizationSystemMd from "./_variants/default/compaction/prompts/summarization-system.md" with { type: "text" };
import caveman_compactionPromptsSummarizationSystemMd from "./_variants/caveman/compaction/prompts/summarization-system.md" with { type: "text" };

// 8 prompts registered.
registerPromptVariants([
	[gentle_compactionPromptsBranchSummaryMd, { default: default_compactionPromptsBranchSummaryMd, caveman: caveman_compactionPromptsBranchSummaryMd }] as const,
	[gentle_compactionPromptsCompactionShortSummaryMd, { default: default_compactionPromptsCompactionShortSummaryMd, caveman: caveman_compactionPromptsCompactionShortSummaryMd }] as const,
	[gentle_compactionPromptsCompactionSummaryContextMd, { default: default_compactionPromptsCompactionSummaryContextMd, caveman: caveman_compactionPromptsCompactionSummaryContextMd }] as const,
	[gentle_compactionPromptsCompactionSummaryMd, { default: default_compactionPromptsCompactionSummaryMd, caveman: caveman_compactionPromptsCompactionSummaryMd }] as const,
	[gentle_compactionPromptsCompactionTurnPrefixMd, { default: default_compactionPromptsCompactionTurnPrefixMd, caveman: caveman_compactionPromptsCompactionTurnPrefixMd }] as const,
	[gentle_compactionPromptsCompactionUpdateSummaryMd, { default: default_compactionPromptsCompactionUpdateSummaryMd, caveman: caveman_compactionPromptsCompactionUpdateSummaryMd }] as const,
	[gentle_compactionPromptsHandoffDocumentMd, { default: default_compactionPromptsHandoffDocumentMd, caveman: caveman_compactionPromptsHandoffDocumentMd }] as const,
	[gentle_compactionPromptsSummarizationSystemMd, { default: default_compactionPromptsSummarizationSystemMd, caveman: caveman_compactionPromptsSummarizationSystemMd }] as const,
]);
