/**
 * MissionControl public surface — imported by `../index.ts` to wire the
 * engine into the pi-missions extension.
 */

export {
	discoverAbortSessionNames,
	executeAbort,
	killOrchSessions,
	planAbortActions,
	selectAbortTargetSessions,
	waitForSessionExit,
	writeWrapUpFiles,
} from "./abort";
export type { SpawnAgentHandle, SpawnAgentOpts } from "./adapter";
export {
	legacyBatchHistoryPath,
	legacyBatchPath,
	missionBatchPath,
	missionHistoryPath,
	missionsDir,
	missionTelemetryDir,
	projectDir,
	spawnAgent,
	supervisorDir,
	supervisorEventsPath,
} from "./adapter";
export type { AgentDef, AgentFile } from "./agent-def";
export {
	loadAgentDef,
	loadBaseAgentPrompt,
	loadLocalAgentPrompt,
	parseAgentFile,
	resetPointerWarning,
	resolveAgentPointerRoot,
} from "./agent-def";
export type {
	AgentEventCallback,
	AgentHostOptions,
	AgentHostResult,
	AgentTelemetryCallback,
} from "./agent-host";
export { spawnHostedAgent } from "./agent-host";
export type {
	LogRotationResult,
	PostIntegrateCleanupResult,
	PreflightCleanupResult,
	PreflightSweepResult,
	PriorBatchCleanupResult,
	SizeCapResult,
	SweepDeps,
} from "./cleanup";
export {
	cleanupPostIntegrate,
	cleanupPriorBatchArtifacts,
	enforceTelemetrySizeCap,
	formatLogRotation,
	formatPostIntegrateCleanup,
	formatPreflightCleanup,
	formatPreflightSweep,
	formatPriorBatchCleanup,
	formatSizeCap,
	LOG_ROTATION_THRESHOLD_BYTES,
	rotateSupervisorLogs,
	runPreflightCleanup,
	STALE_ARTIFACT_MAX_AGE_MS,
	sweepStaleArtifacts,
	TELEMETRY_SIZE_CAP_BYTES,
} from "./cleanup";
export { loadOrchestratorConfig, loadSupervisorConfig, loadTaskRunnerConfig } from "./config";
export type { ConfigLoadErrorCode, GlobalPreferencesLoadResult } from "./config-loader";
export {
	_resetMigrationGuard,
	_resetPointerWarning,
	applyGlobalPreferences,
	ConfigLoadError,
	hasConfigFiles,
	loadGlobalPreferences,
	loadGlobalPreferencesWithMeta,
	loadLayer1Config,
	loadProjectConfig,
	loadProjectOverrides,
	resolveConfigRoot,
	resolveGlobalPreferencesPath,
	resolveTaskRunnerPointer,
	toOrchestratorConfig,
	toTaskConfig,
	toTaskRunnerConfig,
} from "./config-loader";
export type {
	ApprovalPolicy,
	AssignmentConfig,
	ContextConfig,
	DeepPartial,
	DependenciesConfig,
	FailureConfig,
	GlobalPreferences,
	InitAgentDefaultsPreferences,
	MergeConfig,
	MissionPolicy,
	MissionProjectConfig,
	MissionRole,
	MissionRoleModels,
	MissionsSection,
	ModelFallbackMode,
	MonitoringConfig,
	OrchestratorCoreConfig,
	OrchestratorSection,
	PassThreshold,
	PathsConfig,
	PreWarmConfig,
	ProjectMetadataConfig,
	QualityGateConfig,
	ReviewerConfig,
	RiskLevel,
	SecretScannerMode,
	SelfDocTarget,
	StandardsConfig,
	StandardsOverride,
	SupervisorSectionConfig,
	TaskAreaConfig,
	TaskRunnerSection,
	TestingConfig,
	VerificationConfig,
	WorkerConfig,
	WorkspaceRepoSectionConfig,
	WorkspaceRoutingSectionConfig,
	WorkspaceSectionConfig,
} from "./config-schema";
export {
	CONFIG_VERSION,
	DEFAULT_BOOTSTRAP_GLOBAL_PREFERENCES,
	DEFAULT_GLOBAL_PREFERENCES,
	DEFAULT_MISSION_POLICY,
	DEFAULT_MISSIONS_SECTION,
	DEFAULT_ORCHESTRATOR_SECTION,
	DEFAULT_PROJECT_CONFIG,
	DEFAULT_TASK_RUNNER_SECTION,
	GLOBAL_PREFERENCES_FILENAME,
	GLOBAL_PREFERENCES_SUBDIR,
	PROJECT_CONFIG_FILENAME,
} from "./config-schema";
export { FALLBACK_CONTEXT_WINDOW, resolveContextWindow } from "./context-window";
export type { DiagnosticEvent, DiagnosticReportInput } from "./diagnostic-reports";
export {
	assembleDiagnosticInput,
	buildDiagnosticEvents,
	buildMarkdownReport,
	diagnosticsDir,
	emitDiagnosticReports,
	eventsToJsonl,
} from "./diagnostic-reports";
export type {
	DiagnosticExitSummary,
	DiagnosticRetryRecord,
	ExitClassification,
	ExitClassificationInput,
	SessionTokenCounts,
	TaskExitDiagnostic,
} from "./diagnostics";
export {
	CONTEXT_OVERFLOW_THRESHOLD_PCT,
	classifyExit,
	EXIT_CLASSIFICATIONS,
	isModelAccessError,
	MODEL_ACCESS_ERROR_PATTERNS,
} from "./diagnostics";
export type {
	DependencyCacheFile,
	DependencyCandidate,
	DependencyRef,
	DiscoveryOptions,
	ParsedPromptResult,
	ParsedSegmentDagBody,
	ParsedTask,
	StepSegmentParseResult,
} from "./discovery";
export {
	applyDependenciesFromCache,
	buildCompletedTaskSet,
	buildTaskRegistry,
	dedupeAndNormalizeDeps,
	discoverTasks,
	extractCheckboxes,
	extractTaskIdFromFolderName,
	extractTaskName,
	findDependencyCandidates,
	isPathWithin,
	loadAreaDependencyCache,
	normalizeDependencyReference,
	normalizePathForCompare,
	normalizeSegmentRepoToken,
	parseDependencies,
	parseDependencyReference,
	parsePromptForOrchestrator,
	parseSegmentDagMetadata,
	parseStepSegmentMapping,
	resolveArguments,
	resolveDependencies,
	resolveTaskRouting,
	runDiscovery,
	SEGMENT_FALLBACK_REPO_PLACEHOLDER,
	SEGMENT_REPO_ID_PATTERN,
	scanAreaForTasks,
	writeAreaDependencyCache,
} from "./discovery";
export {
	abortBatch,
	advanceWave,
	beginBatch,
	pauseBatch,
	phaseAfterOutcomes,
	promoteToBatch,
	recordTaskOutcome,
	resumeBatch,
	setLaneStatus,
} from "./engine";
export { resolveTaskWorkerAgentId } from "./engine-agent-ids";
export {
	applySegmentExpansionMutation,
	collectProcessedSegmentExpansionRequestIds,
	expansionRequestHasCycle,
	processSegmentExpansionRequestAtBoundary,
	scheduleContinuationSegmentRound,
	upsertPendingExpandedSegmentRecords,
	validateSegmentExpansionRequestAtBoundary,
} from "./engine-expansion";
export {
	advanceMilestonePhase,
	bumpValidationRound,
	canAttemptAnotherValidationRound,
	currentMilestone,
	defaultMilestone,
	emptyFixFeatureSet,
	findMilestone,
	groupWavesIntoMilestones,
	markMilestoneFailed,
	markMilestonePassed,
	milestoneAllFeaturesComplete,
	milestoneAnyFeatureStarted,
	onTaskOutcomeRecorded,
	recomputeMilestones,
	TERMINAL_MILESTONE_STATUSES,
	toBatchMilestone,
	updateMilestoneInArray,
} from "./engine-milestones";
export { buildSegmentFrontierWaves, linearizeTaskSegmentPlan, resolveDisplayWaveNumber } from "./engine-segment-waves";
export { resolveBatchHistoryTaskTokens, taskTokensFromOutcomeTelemetry } from "./engine-tokens";
export type {
	EngineWorkerData,
	SerializedBatchState,
	SerializedWorkspaceConfig,
	WorkerErrorSource,
	WorkerInMessage,
	WorkerToMainMessage,
} from "./engine-worker";
export {
	applySerializedState,
	deserializeWorkspaceConfig,
	serializeBatchForWorker,
	serializeWorkspaceConfig,
} from "./engine-worker";
export { executeIntegration } from "./execute-integration";
export type { MonitorUpdateCallback, ParsedWorktreeStatus } from "./execution";
export {
	buildAgentIdFromLane,
	buildExecutionUnit,
	buildReviewerEnv,
	computeTransitiveDependents,
	ensureTaskFilesCommitted,
	executeLaneV2,
	executeWave,
	executeWithStopAll,
	fileExistsAsync,
	isV2AgentAlive,
	killV2LaneAgents,
	monitorLanes,
	parseStatusMdAtPath,
	parseWorktreeStatusMd,
	parseWorktreeStatusMdAsync,
	readLaneLogTail,
	readLaneLogTailAsync,
	readTaskStatusTail,
	readTaskStatusTailAsync,
	resolveLaneLogPath,
	resolveLaneLogRelativePath,
	resolveRuntimeStateRoot,
	resolveTaskDonePath,
	resolveTaskMonitorState,
	selectRuntimeBackend,
	setV2LivenessRegistryCache,
} from "./execution";
export type { IntegrateArgs, IntegrateMode, ResumeArgs } from "./extension-args";
export { parseIntegrateArgs, parseResumeArgs } from "./extension-args";
export type { DetachEngineRunDeps, Notify, NotifyLevel } from "./extension-async";
export { detachEngineRun } from "./extension-async";
export type {
	GeneratedFixFeature,
	GenerateFixFeaturesOptions,
	ValidatorFinding,
	ValidatorFindingSeverity,
	ValidatorKind,
} from "./fix-features";
export {
	buildFixFeatureId,
	FIX_FEATURE_TEMPLATE_FILENAME,
	generateFixFeatures,
	MaxValidationRoundsExceededError,
	renderTemplate,
	slugify,
} from "./fix-features";
export type { MissionWidget, ModelCheckResult, ThemeLike } from "./formatting";
export {
	buildDashboardViewModel,
	computeMissionSummaryCounts,
	createMissionWidget,
	formatDependencyGraph,
	formatDiscoveryResults,
	formatElapsedTime,
	formatModelValidation,
	formatWavePlan,
	renderLaneCard,
} from "./formatting";
export type { GitResult } from "./git";
export { getCurrentBranch, runGit, runGitWithEnv } from "./git";
export { collectRepoCleanupFindings } from "./integrate-cleanup";
export { resolveIntegrationContext } from "./integration-context";
export { buildCiDeps, buildIntegrationExecutor } from "./integration-executor";
export { killAllMergeAgentsV2, killMergeAgentV2 } from "./killers";
export type { KnowledgeEntry } from "./knowledge";
export {
	appendKnowledgeEntry,
	ingestValidatorLessons,
	KNOWLEDGE_FILENAME,
	KNOWLEDGE_GLOBAL_SCOPE,
	knowledgePath,
	parseKnowledgeText,
	readKnowledgeEntries,
	summariseKnowledge,
} from "./knowledge";
export type { LaneRunnerDeps, LaneRunnerHandle, ReviewerTelemetryContext, SegmentCheckboxCounts } from "./lane-runner";
export {
	buildTaskPrompt,
	getSegmentCheckboxes,
	getStepsForRepoId,
	hasPendingExpansionRequestFiles,
	isSegmentComplete,
	mapLaneSnapshotStatusToWorkerStatus,
	mapLaneTaskStatusToTerminalSnapshotStatus,
	REVIEWER_STATE_STALE_MS,
	readReviewerTelemetrySnapshot,
	startLaneRunner,
} from "./lane-runner";
export { execLog } from "./log";
export type { MailboxAuditEventType, MailboxMessage, MailboxMessageType, WriteMailboxMessageOpts } from "./mailbox";
export {
	_resetRateLimits,
	ackMessage,
	ackOutboxMessage,
	appendMailboxAuditEvent,
	atomicWriteJsonFile,
	broadcastInboxDir,
	checkRateLimit,
	discoverMailboxAgentIds,
	isValidMailboxMessage,
	MAILBOX_DIR_NAME,
	MAILBOX_MAX_CONTENT_BYTES,
	MAILBOX_MESSAGE_TYPES,
	mailboxRoot,
	RATE_LIMIT_WINDOW_MS,
	readInbox,
	readOutbox,
	readOutboxHistory,
	recordSend,
	sessionAckDir,
	sessionInboxDir,
	sessionOutboxDir,
	writeBroadcastMessage,
	writeMailboxMessage,
	writeOutboxMessage,
} from "./mailbox";
export {
	buildMergeRequest,
	classifyMergeHealth,
	determineMergeOrder,
	parseMergeResult,
	parseMergeResultAsync,
} from "./merge";
export { computeIntegrateCleanupResult, MISSION_MESSAGES } from "./messages";
export type { AppliedMigration, Migration, MigrationRunResult, MigrationState, MissionMeta } from "./migrations";
export { loadMissionMeta, MIGRATION_REGISTRY, runMigrations, saveMissionMeta } from "./migrations";
export type { ReconcileMilestoneValidatorsOptions } from "./milestone-resume";
export { reconcileMilestoneValidators } from "./milestone-resume";
export type { MilestoneRuntime, ValidationRoundDeps, ValidationRoundResult } from "./milestone-runner";
export {
	countFixFeaturesForMilestone,
	insertFixFeaturesIntoBatch,
	runValidationRound,
} from "./milestone-runner";
export type { CheckpointInput } from "./mission-checkpoint";
export {
	CHECKPOINTS_DIRNAME,
	checkpointPath,
	checkpointsDir,
	renderCheckpointMarkdown,
	timestampSlug,
	writeMissionCheckpoint,
} from "./mission-checkpoint";
export type { MissionDepsReport } from "./mission-deps";
export { buildMissionDepsReport, parseMissionDepsArgs } from "./mission-deps";
export type { MissionPlanReport } from "./mission-plan";
export { buildMissionPlanReport, parseMissionPlanArgs } from "./mission-plan";
export type { CreateSkillDraftOptions, SkillEntry, TaskSkillContext } from "./mission-skills";
export {
	buildSkillPromptBlock,
	createSkillDraft,
	discardSkillDraft,
	findMatchingSkills,
	listAvailableSkills,
	listDraftSkills,
	listPromotedSkills,
	loadSkillContent,
	normaliseSkillName,
	parseSkillFrontMatter,
	promoteSkillDraft,
	resolveTaskSkills,
	SKILL_DRAFTS_DIRNAME,
	SKILLS_DIRNAME,
	skillDir,
	skillDraftDir,
	skillDraftsRoot,
	skillsRoot,
} from "./mission-skills";
export { detectMissionState } from "./mission-state-detect";
export type { MissionStatusReport } from "./mission-status";
export { buildMissionStatusReport } from "./mission-status";
export type { MissionSessionEntry } from "./missions";
export { formatMissionSessions, listMissionSessions } from "./missions";
export {
	buildBranchName,
	buildLaneSessionId,
	resolveOperatorId,
	resolveRepoSlug,
	sanitizeNameComponent,
} from "./naming";
export type {
	AddAssertionInput,
	ApprovePlanInput,
	CreateMilestoneInput,
	ListSkillsResult,
	MilestoneStatusRow,
	MilestoneWriteResult,
	SetRoleModelInput,
	SetRoleModelResult,
	ValidationStatusResult,
	WriteValidationContractInput,
} from "./orch-handlers";
export {
	handleAddAssertion,
	handleApprovePlan,
	handleCreateMilestone,
	handleKnowledgeEntries,
	handleListSkills,
	handleLoadBatchState,
	handleLoadMilestones,
	handleReadKnowledge,
	handleReadPlanManifest,
	handleReadRoleModels,
	handleReadValidationContract,
	handleReadValidationStatus,
	handleSetRoleModel,
	handleTelemetryRollup,
	handleWriteValidationContract,
} from "./orch-handlers";
export {
	packageFileExists,
	packageRoot,
	resolveAgentTemplate,
	resolvePackageFile,
	resolveTaskTemplate,
} from "./paths";
export {
	analyzeMissionStartupState,
	applyPartialProgressToOutcomes,
	archiveMission,
	buildEngineEventBase,
	buildTier0EventBase,
	clearActiveBatch,
	deleteBatchState,
	detectOrphanSessions,
	emitEngineEvent,
	emitTier0Event,
	getTaskDoneFileCandidates,
	hasTaskDoneMarker,
	loadActiveBatch,
	loadBatchHistory,
	loadBatchState,
	parseMissionSessionNames,
	persistRuntimeState,
	STATE_WRITE_MAX_RETRIES,
	STATE_WRITE_RETRY_DELAY_MS,
	saveActiveBatch,
	saveBatchHistory,
	saveBatchState,
	seedPendingOutcomesForAllocatedLanes,
	serializeBatchState,
	syncTaskOutcomesFromMonitor,
	unlinkBatchState,
	upconvertV1toV2,
	upconvertV2toV3,
	upconvertV3toV4,
	upconvertV4toV5,
	updateBatchHistoryIntegration,
	upsertTaskOutcome,
	VALID_BATCH_PHASES,
	VALID_PERSISTED_MERGE_STATUSES,
	VALID_TASK_STATUSES,
	validatePersistedState,
} from "./persistence";
export type {
	Clarification,
	DraftedFeature,
	DraftFeatureOptions,
	FinalizePlanOptions,
	PlanManifest,
} from "./planning";
export {
	clarificationsPath,
	draftFeature,
	finalizePlan,
	listClarifications,
	loadPlanManifest,
	PLANNING_DIRNAME,
	parseClarifications,
	planManifestPath,
	planningDir,
	recordClarification,
	renderFeaturePrompt,
} from "./planning";
export type { PolicyDecision } from "./policy";
export {
	classifyToolCall,
	DEFAULT_RISK_TABLE,
	DESTRUCTIVE_BASH_PATTERNS,
	evaluateToolCall,
	mergePolicy,
} from "./policy";
export { dropBatchAutostash, selectBatchAutostashIndices, withPreservedMissionHistory } from "./post-integration";
export {
	appendAgentEvent,
	buildRegistrySnapshot,
	cleanupBatchRuntime,
	createManifest,
	detectOrphans,
	getAgentsByRole,
	getLiveAgents,
	isProcessAlive,
	isTerminalStatus,
	markOrphansCrashed,
	readLaneSnapshot,
	readManifest,
	readMergeSnapshot,
	readRegistrySnapshot,
	updateManifestStatus,
	writeLaneSnapshot,
	writeManifest,
	writeMergeSnapshot,
	writeRegistrySnapshot,
} from "./process-registry";
export type {
	FindingCategory,
	FindingSeverity,
	QualityGateContext,
	QualityGateResult,
	ReconciliationAction,
	ReconciliationResult,
	ReviewFinding,
	ReviewVerdict,
	StatusReconciliation,
	VerdictEvaluation,
	VerdictFailReason,
} from "./quality-gate";
export {
	applyStatusReconciliation,
	applyVerdictRules,
	buildFixAgentPrompt,
	FEEDBACK_FILENAME,
	generateFeedbackMd,
	generateQualityGatePrompt,
	parseVerdict,
	readAndEvaluateVerdict,
	VERDICT_FILENAME,
} from "./quality-gate";
export type { DiagnosticCheckResult, PreResumeDiagnosticsResult } from "./resume";
export {
	buildResumeRuntimeWavePlan,
	checkResumeEligibility,
	collectAllRepoRoots,
	collectDoneTaskIdsForResume,
	collectRepoRoots,
	computeResumePoint,
	enrichResumePointWithMilestoneValidators,
	getMergeStatusForWave,
	reconcileTaskStates,
	reconstructAllocatedLanes,
	reconstructSegmentFrontier,
	resolveRepoIdFromRoot,
	runPreResumeDiagnostics,
} from "./resume";
export {
	REVIEWER_POLL_INTERVAL_MS,
	REVIEWER_SHUTDOWN_SIGNAL,
	REVIEWER_SIGNAL_PREFIX,
	REVIEWER_WAIT_TIMEOUT_MS,
	reviewerExtension,
} from "./reviewer";
export type { ModelSource, ResolvedRoleModel } from "./role-models";
export {
	applyRoleModelOverride,
	describeAllRoleModels,
	describeModelResolution,
	isMissionRole,
	MISSION_ROLES,
	persistRoleModelOverride,
	projectConfigPath,
	resolveModelForRole,
} from "./role-models";
export type { Engine, EngineDeps } from "./runtime";
export { createEngine } from "./runtime";
export type { ScanVerdict, SecretMatch, SecretPattern } from "./secret-scanner";
export {
	BUILTIN_SECRET_PATTERNS,
	compileExtraPatterns,
	evaluateTextForSecrets,
	redactSecret,
	scanForSecrets,
	scanWithPolicy,
	verdictForMatches,
} from "./secret-scanner";
export type { SidecarTailState, SidecarTelemetryDelta } from "./sidecar-telemetry";
export { createSidecarTailState, tailSidecarJsonl } from "./sidecar-telemetry";
export type { EngineEventSummary, SupervisorHandle } from "./supervisor";
export {
	ACTION_CLASSIFICATION_EXAMPLES,
	activateSupervisor,
	appendAuditEntry,
	auditTrailPath,
	bufferDigestEvent,
	buildAutonomyDescription,
	buildGuardrailsSection,
	buildIntegrationPlan,
	buildRoutingSystemPrompt,
	buildSupervisorSystemPrompt,
	buildTakeoverSummary,
	collectBatchSummaryData,
	deactivateSupervisor,
	detectBranchProtection,
	formatBatchSummary,
	formatDurationMs,
	formatEventNotification,
	formatIntegrationOutcome,
	formatIntegrationPlan,
	formatTaskDigest,
	freshDigestBuffer,
	freshEventTailerState,
	freshSupervisorState,
	generateBatchSummary,
	hasGitRemotes,
	isBatchTerminal,
	isDigestEmpty,
	isLockStale,
	isSupervisorProcessAlive,
	loadSupervisorTemplate,
	lockfilePath,
	logRecoveryAction,
	mergePr,
	parseJsonlLines,
	parseSupervisorTemplate,
	pollPrCiStatus,
	processEvents,
	readAuditTrail,
	readEngineEventsForBatch,
	readLockfile,
	readLockfileAsync,
	readNewBytes,
	readNewBytesAsync,
	readTier0EventsForBatch,
	removeLockfile,
	replaceTemplateVars,
	requiresConfirmation,
	resolveBaseTemplatePath,
	resolvePrimerPath,
	resolveSupervisorConfig,
	shouldNotify,
	writeLockfile,
	writeLockfileAsync,
} from "./supervisor";
export type { CoreParsedTask, ParsedStatus, StepInfo } from "./task-executor-core";
export {
	appendTableRow,
	displayName,
	extractVerdict,
	findStepBoundaryCommit,
	generateReviewRequest,
	generateStatusMd,
	getHeadCommitSha,
	isLowRiskStep,
	isStepComplete,
	logExecution,
	logReview,
	parsePromptMd,
	parseStatusMd,
	resolveStandards,
	sanitizeSteeringContent,
	updateStatusField,
	updateStepStatus,
} from "./task-executor-core";
export type { ResolvedTaskPaths } from "./task-paths";
export { resolveCanonicalTaskPaths } from "./task-paths";
export type {
	DurationBucket,
	MissionRollup,
	RoleRollup,
	TelemetryRole,
	TelemetrySample,
} from "./telemetry-rollup";
export {
	bucketDurations,
	DEFAULT_DURATION_BUCKETS,
	extractDurations,
	rollupBatchState,
	rollupTelemetry,
	TELEMETRY_ROLES,
	taskRecordToSample,
} from "./telemetry-rollup";
export type { LaneSessionAliasTarget } from "./tmux-compat";
export { normalizeLaneSessionAlias, readLaneSessionAliases } from "./tmux-compat";
export type {
	AbortActionStep,
	AbortErrorCode,
	AbortLaneResult,
	AbortMode,
	AbortResult,
	AbortTargetSession,
	AllocatedLane,
	AllocatedTask,
	AllocationErrorCode,
	AuditTrailEntry,
	Autonomy,
	BatchDiagnostics,
	BatchHistorySummary,
	BatchSummaryData,
	BatchTaskSummary,
	BatchWaveSummary,
	BranchProtectionStatus,
	BulkWorktreeError,
	CiDeps,
	CreateLaneWorktreesResult,
	CreateWorktreeOptions,
	DependencyGraph,
	DiscoveryError,
	DiscoveryResult,
	EngineEvent,
	EngineEventCallback,
	EngineEventType,
	EngineStatus,
	EnsureBranchDeletedResult,
	EscalationContext,
	EventTailerState,
	ExecutionErrorCode,
	ExecutionUnit,
	GraphValidationResult,
	IntegrateCleanupRepoFindings,
	IntegrateCleanupResult,
	IntegrationContext,
	IntegrationContextError,
	IntegrationDeps,
	IntegrationExecDeps,
	IntegrationExecutor,
	IntegrationPlan,
	IntegrationResult,
	LaneAssignment,
	LaneExecutionResult,
	LaneMonitorSnapshot,
	LaneTaskOutcome,
	LaneTaskOutcomeTelemetry,
	LaneTaskStatus,
	LockfileCheckResult,
	MergeConflict,
	MergeErrorCode,
	MergeHealthEventType,
	MergeHealthStatus,
	MergeLaneResult,
	MergeResult,
	MergeResultStatus,
	MergeSessionHealthState,
	MergeSessionSnapshot,
	MergeVerification,
	MergeWaveResult,
	Milestone,
	MilestoneStatus,
	MilestoneValidatorReconciliation,
	MilestoneValidatorSlot,
	MissionBatchPhase,
	MissionBatchRuntimeState,
	MissionControlConfig,
	MissionDashboardViewModel,
	MissionLaneCardData,
	MissionProjectState,
	MissionStateDetection,
	MissionStateDetectionDeps,
	MissionSummaryCounts,
	ModelCheckEntry,
	MonitorState,
	MtimeTracker,
	OrchestratorConfig,
	OrphanDetectionResult,
	OrphanRecommendedAction,
	OrphanStateStatus,
	PacketPaths,
	ParsedSupervisorEvent,
	PendingSegmentExpansionRequest,
	PersistedBatchState,
	PersistedLaneRecord,
	PersistedMergeResult,
	PersistedRepairRecord,
	PersistedRepoMergeOutcome,
	PersistedSegmentRecord,
	PersistedSegmentStatus,
	PersistedTaskExitSummary,
	PersistedTaskRecord,
	PointerResolution,
	PreflightCheck,
	PreflightResult,
	PreserveBranchErrorCode,
	PreserveBranchResult,
	PromoteBatchOptions,
	PromptSegmentDagEdge,
	PromptSegmentDagMetadata,
	ReconciledTaskState,
	RecoveryActionClassification,
	RemoveAllWorktreesResult,
	RemoveWorktreeOutcome,
	RemoveWorktreeResult,
	RepoMergeOutcome,
	ResilienceState,
	ResolvedModelInfo,
	ResumeEligibility,
	ResumePoint,
	RuntimeAgentEvent,
	RuntimeAgentEventType,
	RuntimeAgentId,
	RuntimeAgentManifest,
	RuntimeAgentRole,
	RuntimeAgentStatus,
	RuntimeAgentTelemetrySnapshot,
	RuntimeBackend,
	RuntimeBackendSelection,
	RuntimeLaneSnapshot,
	RuntimeMergeSnapshot,
	RuntimeRegistry,
	RuntimeTaskProgress,
	RuntimeWaveAssignment,
	SegmentCheckboxGroup,
	SegmentEdgeProvenance,
	SegmentExpansionEdge,
	SegmentExpansionRequest,
	SegmentFrontierResult,
	SegmentFrontierTaskState,
	SegmentId,
	SegmentLifecycleStatus,
	StateFileErrorCode,
	StepSegmentMapping,
	SupervisorAlert,
	SupervisorAlertCallback,
	SupervisorAlertCategory,
	SupervisorAlertContext,
	SupervisorAutonomyLevel,
	SupervisorConfig,
	SupervisorLockfile,
	SupervisorRoutingContext,
	SupervisorSegmentFrontierSnapshot,
	SupervisorState,
	SupervisorSummaryDeps,
	TaskArea,
	TaskDigestBuffer,
	TaskMonitorSnapshot,
	TaskRunnerConfig,
	TaskSegmentEdge,
	TaskSegmentNode,
	TaskSegmentPlan,
	TaskSegmentPlanMap,
	Tier0EscalationPattern,
	Tier0Event,
	Tier0EventSummary,
	Tier0EventType,
	Tier0RecoveryPattern,
	TokenCounts,
	UnifiedEventType,
	VerificationBaselineResult,
	WaveComputationResult,
	WaveExecutionResult,
	WorkspaceConfig,
	WorkspaceConfigErrorCode,
	WorkspaceMode,
	WorkspaceRepoConfig,
	WorkspaceRoutingConfig,
	WorktreeErrorCode,
	WorktreeInfo,
} from "./types";
export {
	AllocationError,
	BATCH_HISTORY_MAX_ENTRIES,
	BATCH_STATE_SCHEMA_VERSION,
	buildExpansionRequestId,
	buildRuntimeAgentId,
	buildSegmentId,
	DEFAULT_MILESTONE_ID,
	DEFAULT_MILESTONE_MAX_VALIDATION_ROUNDS,
	DEFAULT_MISSIONCONTROL_CONFIG,
	DEFAULT_ORCHESTRATOR_CONFIG,
	DEFAULT_SUPERVISOR_CONFIG,
	DIGEST_SUPERVISOR_EVENT_TYPES,
	DONE_GRACE_MS,
	DURATION_BASE_MINUTES,
	defaultBatchDiagnostics,
	defaultResilienceState,
	EVENT_POLL_INTERVAL_MS,
	EXECUTION_POLL_INTERVAL_MS,
	ExecutionError,
	FATAL_DISCOVERY_CODES,
	freshMissionBatchState,
	generateBatchId,
	getTaskDurationMinutes,
	HEARTBEAT_INTERVAL_MS,
	MERGE_HEALTH_CAPTURE_LINES,
	MERGE_HEALTH_POLL_INTERVAL_MS,
	MERGE_HEALTH_STUCK_THRESHOLD_MS,
	MERGE_HEALTH_WARNING_THRESHOLD_MS,
	MERGE_POLL_INTERVAL_MS,
	MERGE_RESULT_GRACE_MS,
	MERGE_RESULT_READ_RETRIES,
	MERGE_RESULT_READ_RETRY_DELAY_MS,
	MERGE_SPAWN_RETRY_MAX,
	MERGE_TIMEOUT_MAX_RETRIES,
	MERGE_TIMEOUT_MS,
	MergeError,
	POINTER_FILENAME,
	parseSegmentIdRepo,
	resolvePacketPaths,
	runtimeAgentDir,
	runtimeAgentEventsPath,
	runtimeLaneSnapshotPath,
	runtimeManifestPath,
	runtimeMergeSnapshotPath,
	runtimeRegistryPath,
	runtimeRoot,
	SESSION_SPAWN_RETRY_MAX,
	SIGNIFICANT_SUPERVISOR_EVENT_TYPES,
	SIZE_DURATION_MINUTES,
	STALE_LOCK_THRESHOLD_MS,
	StateFileError,
	TASK_DIGEST_INTERVAL_MS,
	TERMINAL_AGENT_STATUSES,
	TERMINAL_BATCH_PHASES,
	VALID_MERGE_STATUSES,
	validateAgentManifest,
	validatePacketPaths,
	WORKSPACE_CONFIG_FILENAME,
	WorkspaceConfigError,
	WorktreeError,
} from "./types";
export type { ValidateModelDeps } from "./validate-models";
export { validateModelAvailability } from "./validate-models";
export type {
	AssertionId,
	BehavioralAssertion,
	ValidationContract,
} from "./validation-contract";
export {
	addAssertion,
	assertionsForMilestone,
	createEmptyContract,
	findAssertion,
	loadValidationContract,
	saveValidationContract,
	VALIDATION_CONTRACT_FILENAME,
	VALIDATION_CONTRACT_SCHEMA_VERSION,
	validateAssertionId,
	validateContractShape,
	validationContractPath,
} from "./validation-contract";
export type { ValidatorRunOutcome, WithStallTimeoutOptions } from "./validator-stall";
export {
	DEFAULT_HEARTBEAT_INTERVAL_MS,
	DEFAULT_VALIDATOR_STALL_TIMEOUT_MS,
	elapsedDays,
	heartbeatAgeMs,
	idleSinceLabel,
	isHeartbeatStale,
	withStallTimeout,
} from "./validator-stall";
export type {
	MilestoneValidationRound,
	MilestoneValidatorOutput,
	MilestoneValidatorVerdict,
	SpawnScrutinyValidatorOptions,
	SpawnUserTestingValidatorOptions,
} from "./validators";
export {
	combineValidatorVerdicts,
	MILESTONE_VALIDATOR_SCHEMA_VERSION,
	mergeValidatorRound,
	parseMilestoneValidatorResult,
	parseScrutinyValidatorResult,
	parseUserTestingValidatorResult,
	renderScrutinyPrompt,
	renderUserTestingPrompt,
	spawnScrutinyValidator,
	spawnUserTestingValidator,
	unionFindings,
	unionLessons,
	validationOutputDir,
	validationOutputPath,
} from "./validators";
export type {
	CommandResult,
	FingerprintDiff,
	TestFingerprint,
	VerificationBaseline,
	VerificationCommand,
} from "./verification";
export {
	captureBaseline,
	deduplicateFingerprints,
	diffFingerprints,
	fingerprintKey,
	normalizeFilePath,
	normalizeMessage,
	parseTestOutput,
	parseVitestOutput,
	runVerificationCommands,
} from "./verification";
export type {
	GlobalLaneEntry,
	InferredRepoOrder,
	RepoTaskGroup,
	SegmentPlanBuildOptions,
	WaveComputationOptions,
} from "./waves";
export {
	type AllocateLanesResult,
	allocateLanes,
	applyFileScopeAffinity,
	assignTasksToLanes,
	buildDependencyGraph,
	buildSegmentPlanForTask,
	buildTaskSegmentPlans,
	chunkIntoWaves,
	computeWaveAssignments,
	computeWaves,
	enforceGlobalLaneCap,
	generateLaneId,
	generateLaneSessionId,
	groupTasksByRepo,
	inferTaskRepoOrder,
	isGlobScope,
	nextWaveIndex,
	normalizeScope,
	pathStartsWithSegment,
	prefixOfGlob,
	resolveBaseBranch,
	resolveRepoRoot,
	scopesOverlap,
	taskScopesOverlap,
	tasksRemaining,
	validateAllocationInputs,
	validateGraph,
} from "./waves";
export {
	canonicalizePath,
	loadWorkspaceConfig,
	pointerFilePath,
	resolvePointer,
	workspaceConfigPath,
} from "./workspace";
export type {
	ParsedWorktreeEntry,
	PreserveFailedLaneProgressResult,
	ResolveRepoContext,
	SavedBranchResolution,
	SavePartialProgressResult,
	StaleBranchCleanupResult,
	UnmergedCommitsErrorCode,
	UnmergedCommitsResult,
} from "./worktree";
export {
	computePartialProgressBranchName,
	computeSavedBranchName,
	createLaneWorktrees,
	createWorktree,
	deleteBranchBestEffort,
	deleteStaleBranches,
	ensureBatchContainerDir,
	ensureBranchDeleted,
	ensureLaneWorktrees,
	escapeRegex,
	execCheck,
	forceCleanupWorktree,
	formatPreflightResults,
	generateBatchContainerName,
	generateBatchContainerPath,
	generateBranchName,
	generateMergeWorktreePath,
	generateWorktreePath,
	hasUnmergedCommits,
	isRegisteredWorktree,
	isRetriableRemoveError,
	listWorktrees,
	meetsMinVersion,
	normalizePath,
	parseVersion,
	parseWorktreeList,
	preserveBranch,
	preserveFailedLaneProgress,
	preserveSkippedLaneProgress,
	removeAllWorktrees,
	removeBatchContainerIfEmpty,
	removeWorktree,
	resetWorktree,
	resolveSavedBranchCollision,
	resolveWorktreeBasePath,
	runPreflight,
	safeResetWorktree,
	savePartialProgress,
	sleepAsync,
	sleepSync,
} from "./worktree";
