/**
 * MissionControl dashboard server.
 *
 * Serves the React SPA + JSON API for mission management. Mirrors the
 * `packages/stats` architecture: Bun.serve, static file serving with
 * embedded-bundle fallback for compiled binaries, and REST + SSE endpoints.
 */

import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { $ } from "bun";
import { getMission, getMissionEvents, getMissionTelemetrySummary, listMissions } from "./dashboard-api";
import { abortBatch, loadActiveBatch, pauseBatch, resumeBatch, saveActiveBatch } from "./missioncontrol";

const CLIENT_DIR = path.join(import.meta.dir, "client");
const STATIC_DIR = path.join(import.meta.dir, "..", "dist", "client");
const IS_BUN_COMPILED =
	Bun.env.PI_COMPILED ||
	import.meta.url.includes("$bunfs") ||
	import.meta.url.includes("~BUN") ||
	import.meta.url.includes("%7EBUN");

const COMPILED_CLIENT_DIR_ROOT = path.join(os.tmpdir(), "omp-missions-client");
let compiledClientDirPromise: Promise<string> | null = null;

// -- Embedded client archive ------------------------------------------------
// NOTE: The base64 archive is generated by `bun run build.ts`. During
// development the file may be empty — we fall back to building on demand.
let embeddedClientArchiveTxt = "";
try {
	const embedded = await import("./embedded-client.generated.txt" as string, { with: { type: "text" } }).catch(
		() => null,
	);
	if (embedded && typeof embedded.default === "string") {
		embeddedClientArchiveTxt = embedded.default;
	}
} catch {
	embeddedClientArchiveTxt = "";
}

const getEmbeddedClientArchive = (() => {
	const txt = embeddedClientArchiveTxt.replaceAll(/[\s\r\n]/g, "").trim();
	if (!txt) return null;
	return () => Buffer.from(txt, "base64");
})();

function sanitizeArchivePath(archivePath: string): string | null {
	const normalized = archivePath.replaceAll("\\", "/").replace(/^\.\//, "");
	if (!normalized || normalized === ".") return null;
	if (normalized.includes("..") || path.isAbsolute(normalized)) return null;
	return normalized;
}

async function extractEmbeddedClientArchive(archiveBytes: Buffer, outputDir: string): Promise<void> {
	const archive = new Bun.Archive(archiveBytes);
	const files = await archive.files();
	const extractRoot = path.resolve(outputDir);

	for (const [archivePath, file] of files) {
		const sanitizedPath = sanitizeArchivePath(archivePath);
		if (!sanitizedPath) continue;
		const destinationPath = path.resolve(extractRoot, sanitizedPath);
		if (!destinationPath.startsWith(extractRoot + path.sep)) {
			throw new Error(`Archive entry escapes extraction directory: ${archivePath}`);
		}
		await Bun.write(destinationPath, file);
	}
}

async function getCompiledClientDir(): Promise<string> {
	if (!IS_BUN_COMPILED) return STATIC_DIR;
	if (compiledClientDirPromise) return compiledClientDirPromise;

	const archiveBytes = getEmbeddedClientArchive?.();
	if (!archiveBytes) {
		throw new Error("Compiled MissionControl client bundle missing. Rebuild binary with embedded assets.");
	}

	compiledClientDirPromise = (async () => {
		const bundleHash = Bun.hash(archiveBytes).toString(16);
		const outputDir = path.join(COMPILED_CLIENT_DIR_ROOT, bundleHash);
		const markerPath = path.join(outputDir, "index.html");
		try {
			const marker = await fs.stat(markerPath);
			if (marker.isFile()) return outputDir;
		} catch {}

		await fs.rm(outputDir, { recursive: true, force: true });
		await fs.mkdir(outputDir, { recursive: true });
		await extractEmbeddedClientArchive(archiveBytes, outputDir);
		return outputDir;
	})();

	return compiledClientDirPromise;
}

async function getLatestMtime(dir: string): Promise<number> {
	const entries = await fs.readdir(dir, { withFileTypes: true });
	const promises: Promise<number>[] = [];
	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			promises.push(getLatestMtime(fullPath));
		} else if (entry.isFile()) {
			promises.push(fs.stat(fullPath).then(s => s.mtimeMs));
		}
	}
	let latest = 0;
	const results = await Promise.allSettled(promises);
	for (const r of results) {
		if (r.status === "fulfilled") latest = Math.max(latest, r.value);
	}
	return latest;
}

async function ensureClientBuild(): Promise<void> {
	if (IS_BUN_COMPILED) return;
	const indexPath = path.join(STATIC_DIR, "index.html");
	const cssPath = path.join(STATIC_DIR, "styles.css");
	let clientSourceMtime = 0;
	try {
		clientSourceMtime = await getLatestMtime(CLIENT_DIR);
	} catch {
		// No client directory yet — nothing to build.
		return;
	}
	const tailwindConfigPath = path.join(import.meta.dir, "..", "tailwind.config.js");
	let tailwindConfigMtime = 0;
	try {
		const tailwindConfigStats = await fs.stat(tailwindConfigPath);
		tailwindConfigMtime = tailwindConfigStats.mtimeMs;
	} catch {}
	const sourceMtime = Math.max(clientSourceMtime, tailwindConfigMtime);
	let shouldBuild = true;
	try {
		const [indexStats, cssStats] = await Promise.all([fs.stat(indexPath), fs.stat(cssPath)]);
		if (
			indexStats.isFile() &&
			cssStats.isFile() &&
			indexStats.mtimeMs >= sourceMtime &&
			cssStats.mtimeMs >= sourceMtime
		) {
			shouldBuild = false;
		}
	} catch {
		shouldBuild = true;
	}

	if (!shouldBuild) return;

	await fs.rm(STATIC_DIR, { recursive: true, force: true });

	console.log("Building MissionControl client...");
	const packageRoot = path.join(import.meta.dir, "..");
	const buildResult = await $`bun run build.ts`.cwd(packageRoot).quiet().nothrow();
	if (buildResult.exitCode !== 0) {
		const output = buildResult.text().trim();
		const details = output ? `\n${output}` : "";
		throw new Error(`Failed to build MissionControl client (exit ${buildResult.exitCode})${details}`);
	}
}

// ---------------------------------------------------------------------------
// API
// ---------------------------------------------------------------------------

function jsonResponse(data: unknown, init: ResponseInit = {}): Response {
	return new Response(JSON.stringify(data), {
		...init,
		headers: { "Content-Type": "application/json", ...(init.headers ?? {}) },
	});
}

async function handleApi(req: Request, cwd: string): Promise<Response> {
	const url = new URL(req.url);
	const p = url.pathname;

	if (p === "/api/missions" && req.method === "GET") {
		const missions = await listMissions(cwd);
		return jsonResponse(missions);
	}

	const detailMatch = p.match(/^\/api\/mission\/([^/]+)$/);
	if (detailMatch && req.method === "GET") {
		const detail = await getMission(cwd, detailMatch[1]);
		if (!detail) return new Response("Not Found", { status: 404 });
		return jsonResponse(detail);
	}

	const eventsMatch = p.match(/^\/api\/mission\/([^/]+)\/events$/);
	if (eventsMatch && req.method === "GET") {
		const role = url.searchParams.get("role") ?? "worker";
		const events = await getMissionEvents(cwd, eventsMatch[1], role);
		return jsonResponse({ events });
	}

	const streamMatch = p.match(/^\/api\/mission\/([^/]+)\/stream$/);
	if (streamMatch && req.method === "GET") {
		return buildSSEStream(cwd, streamMatch[1]);
	}

	const telemetryMatch = p.match(/^\/api\/mission\/([^/]+)\/telemetry$/);
	if (telemetryMatch && req.method === "GET") {
		const summary = await getMissionTelemetrySummary(cwd, telemetryMatch[1]);
		return jsonResponse(summary ?? {});
	}

	const controlMatch = p.match(/^\/api\/mission\/([^/]+)\/(pause|resume|abort)$/);
	if (controlMatch && req.method === "POST") {
		const [, id, action] = controlMatch;
		const state = await loadActiveBatch(cwd);
		if (!state?.batch || (state.batch.batchId !== id && id !== "active")) {
			return new Response("No active batch mission", { status: 404 });
		}
		let next = state;
		if (action === "pause") next = pauseBatch(state);
		else if (action === "resume") next = resumeBatch(state);
		else if (action === "abort") {
			const body = (await req.json().catch(() => ({}))) as { reason?: string };
			next = abortBatch(state, body.reason ?? "aborted via dashboard");
		}
		await saveActiveBatch(cwd, next);
		return jsonResponse({ ok: true, phase: next.batch?.phase });
	}

	return new Response("Not Found", { status: 404 });
}

function buildSSEStream(cwd: string, missionId: string): Response {
	const encoder = new TextEncoder();
	const stream = new ReadableStream({
		async start(controller) {
			let cancelled = false;

			const send = (payload: unknown): void => {
				if (cancelled) return;
				controller.enqueue(encoder.encode(`data: ${JSON.stringify(payload)}\n\n`));
			};

			const tick = async (): Promise<void> => {
				const detail = await getMission(cwd, missionId);
				send({ type: "snapshot", detail });
			};

			await tick();
			const interval = setInterval(() => {
				if (cancelled) return;
				void tick();
			}, 2000);

			(controller as ReadableStreamDefaultController & { signal?: AbortSignal }).signal?.addEventListener?.(
				"abort",
				() => {
					cancelled = true;
					clearInterval(interval);
				},
			);
		},
	});
	return new Response(stream, {
		headers: {
			"Content-Type": "text/event-stream",
			"Cache-Control": "no-cache",
			Connection: "keep-alive",
		},
	});
}

async function handleStatic(requestPath: string): Promise<Response> {
	const staticDir = IS_BUN_COMPILED ? await getCompiledClientDir() : STATIC_DIR;
	const filePath = requestPath === "/" ? "/index.html" : requestPath;
	const fullPath = path.join(staticDir, filePath);

	const file = Bun.file(fullPath);
	if (await file.exists()) return new Response(file);

	const index = Bun.file(path.join(staticDir, "index.html"));
	if (await index.exists()) return new Response(index);

	return placeholderPage();
}

function placeholderPage(): Response {
	const body = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>MissionControl</title></head>
<body style="font-family: system-ui; padding: 40px; max-width: 640px; margin: auto;">
  <h1>MissionControl</h1>
  <p>Dashboard is running but the client bundle has not been built yet.</p>
  <p>Run <code>bun run build</code> inside <code>packages/pi-missions</code> to generate the UI.</p>
  <h2>API</h2>
  <ul>
    <li><a href="/api/missions">/api/missions</a></li>
  </ul>
</body>
</html>`;
	return new Response(body, { headers: { "Content-Type": "text/html" } });
}

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

export interface StartServerOptions {
	port?: number;
	cwd?: string;
}

export async function startServer(options: StartServerOptions = {}): Promise<{ port: number; stop: () => void }> {
	await ensureClientBuild();
	const cwd = options.cwd ?? process.cwd();
	const port = options.port ?? 3848;

	const server = Bun.serve({
		port,
		async fetch(req) {
			const url = new URL(req.url);
			const p = url.pathname;

			const corsHeaders = {
				"Access-Control-Allow-Origin": "*",
				"Access-Control-Allow-Methods": "GET, POST, OPTIONS",
				"Access-Control-Allow-Headers": "Content-Type",
			};

			if (req.method === "OPTIONS") {
				return new Response(null, { headers: corsHeaders });
			}

			try {
				const response = p.startsWith("/api/") ? await handleApi(req, cwd) : await handleStatic(p);

				const headers = new Headers(response.headers);
				for (const [k, v] of Object.entries(corsHeaders)) headers.set(k, v);
				return new Response(response.body, { status: response.status, headers });
			} catch (error) {
				console.error("MissionControl server error:", error);
				return jsonResponse(
					{ error: error instanceof Error ? error.message : "Unknown error" },
					{ status: 500, headers: corsHeaders },
				);
			}
		},
	});

	return {
		port: server.port ?? port,
		stop: () => server.stop(),
	};
}
