/**
 * MissionControl dashboard server.
 *
 * Serves the React SPA + JSON API for mission management. Mirrors the
 * `packages/stats` architecture: Bun.serve, static file serving with
 * embedded-bundle fallback for compiled binaries, and REST + SSE endpoints.
 */

import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { isEnoent, logger } from "@oh-my-pi/pi-utils";
import { $ } from "bun";
import {
	appendSupervisorConversation,
	getMission,
	getMissionActivity,
	getMissionAgentStatus,
	getMissionEvents,
	getMissionTelemetrySummary,
	getSupervisorDetail,
	listMissions,
} from "./dashboard-api";
import { dispatchStartRequest, getDefaultToken, type MissionStartRequest } from "./gui-bridge";
import type { BehavioralAssertion } from "./missioncontrol";
import {
	abortBatch,
	handleApprovePlan,
	handleCreateMilestone,
	handleKnowledgeEntries,
	handleListSkills,
	handleLoadMilestones,
	handleReadKnowledge,
	handleReadPlanManifest,
	handleReadRoleModels,
	handleReadValidationContract,
	handleReadValidationStatus,
	handleSetRoleModel,
	handleTelemetryRollup,
	handleWriteValidationContract,
	loadActiveBatch,
	mailboxRoot,
	missionHistoryPath,
	missionsDir,
	pauseBatch,
	readAuditTrail,
	readRegistrySnapshot,
	resumeBatch,
	runtimeAgentEventsPath,
	saveActiveBatch,
	supervisorEventsPath,
} from "./missioncontrol";
import { readDashboardPreferences, writeDashboardPreferences } from "./preferences";
import { getMissionServerHooks, type MissionMetaPatch } from "./server-hooks";

const CLIENT_DIR = path.join(import.meta.dir, "client");
const STATIC_DIR = path.join(import.meta.dir, "..", "dist", "client");
const IS_BUN_COMPILED =
	Bun.env.PI_COMPILED ||
	import.meta.url.includes("$bunfs") ||
	import.meta.url.includes("~BUN") ||
	import.meta.url.includes("%7EBUN");

const COMPILED_CLIENT_DIR_ROOT = path.join(os.tmpdir(), "omp-missions-client");
let compiledClientDirPromise: Promise<string> | null = null;

// -- Embedded client archive ------------------------------------------------
// NOTE: The base64 archive is generated by `bun run build.ts`. During
// development the file may be empty — we fall back to building on demand.
let embeddedClientArchiveTxt = "";
try {
	const embedded = await import("./embedded-client.generated.txt" as string, { with: { type: "text" } }).catch(
		() => null,
	);
	if (embedded && typeof embedded.default === "string") {
		embeddedClientArchiveTxt = embedded.default;
	}
} catch {
	embeddedClientArchiveTxt = "";
}

const getEmbeddedClientArchive = (() => {
	const txt = embeddedClientArchiveTxt.replaceAll(/[\s\r\n]/g, "").trim();
	if (!txt) return null;
	return () => Buffer.from(txt, "base64");
})();

function sanitizeArchivePath(archivePath: string): string | null {
	const normalized = archivePath.replaceAll("\\", "/").replace(/^\.\//, "");
	if (!normalized || normalized === ".") return null;
	if (normalized.includes("..") || path.isAbsolute(normalized)) return null;
	return normalized;
}

async function extractEmbeddedClientArchive(archiveBytes: Buffer, outputDir: string): Promise<void> {
	const archive = new Bun.Archive(archiveBytes);
	const files = await archive.files();
	const extractRoot = path.resolve(outputDir);

	for (const [archivePath, file] of files) {
		const sanitizedPath = sanitizeArchivePath(archivePath);
		if (!sanitizedPath) continue;
		const destinationPath = path.resolve(extractRoot, sanitizedPath);
		if (!destinationPath.startsWith(extractRoot + path.sep)) {
			throw new Error(`Archive entry escapes extraction directory: ${archivePath}`);
		}
		await Bun.write(destinationPath, file);
	}
}

async function getCompiledClientDir(): Promise<string> {
	if (!IS_BUN_COMPILED) return STATIC_DIR;
	if (compiledClientDirPromise) return compiledClientDirPromise;

	const archiveBytes = getEmbeddedClientArchive?.();
	if (!archiveBytes) {
		throw new Error("Compiled MissionControl client bundle missing. Rebuild binary with embedded assets.");
	}

	compiledClientDirPromise = (async () => {
		const bundleHash = Bun.hash(archiveBytes).toString(16);
		const outputDir = path.join(COMPILED_CLIENT_DIR_ROOT, bundleHash);
		const markerPath = path.join(outputDir, "index.html");
		try {
			const marker = await fs.stat(markerPath);
			if (marker.isFile()) return outputDir;
		} catch {}

		await fs.rm(outputDir, { recursive: true, force: true });
		await fs.mkdir(outputDir, { recursive: true });
		await extractEmbeddedClientArchive(archiveBytes, outputDir);
		return outputDir;
	})();

	return compiledClientDirPromise;
}

async function getLatestMtime(dir: string): Promise<number> {
	const entries = await fs.readdir(dir, { withFileTypes: true });
	const promises: Promise<number>[] = [];
	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			promises.push(getLatestMtime(fullPath));
		} else if (entry.isFile()) {
			promises.push(fs.stat(fullPath).then(s => s.mtimeMs));
		}
	}
	let latest = 0;
	const results = await Promise.allSettled(promises);
	for (const r of results) {
		if (r.status === "fulfilled") latest = Math.max(latest, r.value);
	}
	return latest;
}

async function ensureClientBuild(): Promise<void> {
	if (IS_BUN_COMPILED) return;
	const indexPath = path.join(STATIC_DIR, "index.html");
	const cssPath = path.join(STATIC_DIR, "styles.css");
	let clientSourceMtime = 0;
	try {
		clientSourceMtime = await getLatestMtime(CLIENT_DIR);
	} catch {
		// No client directory yet — nothing to build.
		return;
	}
	const tailwindConfigPath = path.join(import.meta.dir, "..", "tailwind.config.js");
	let tailwindConfigMtime = 0;
	try {
		const tailwindConfigStats = await fs.stat(tailwindConfigPath);
		tailwindConfigMtime = tailwindConfigStats.mtimeMs;
	} catch {}
	const sourceMtime = Math.max(clientSourceMtime, tailwindConfigMtime);
	let shouldBuild = true;
	try {
		const [indexStats, cssStats] = await Promise.all([fs.stat(indexPath), fs.stat(cssPath)]);
		if (
			indexStats.isFile() &&
			cssStats.isFile() &&
			indexStats.mtimeMs >= sourceMtime &&
			cssStats.mtimeMs >= sourceMtime
		) {
			shouldBuild = false;
		}
	} catch {
		shouldBuild = true;
	}

	if (!shouldBuild) return;

	await fs.rm(STATIC_DIR, { recursive: true, force: true });

	logger.debug("[missioncontrol] building client");
	const packageRoot = path.join(import.meta.dir, "..");
	const buildResult = await $`bun run build.ts`.cwd(packageRoot).quiet().nothrow();
	if (buildResult.exitCode !== 0) {
		const output = buildResult.text().trim();
		const details = output ? `\n${output}` : "";
		throw new Error(`Failed to build MissionControl client (exit ${buildResult.exitCode})${details}`);
	}
}

// ---------------------------------------------------------------------------
// API
// ---------------------------------------------------------------------------

function jsonResponse(data: unknown, init: ResponseInit = {}): Response {
	return new Response(JSON.stringify(data), {
		...init,
		headers: { "Content-Type": "application/json", ...(init.headers ?? {}) },
	});
}

async function handleApi(req: Request, cwd: string): Promise<Response> {
	const url = new URL(req.url);
	const p = url.pathname;

	if (p === "/api/missions" && req.method === "GET") {
		const missions = await listMissions(cwd);
		return jsonResponse(missions);
	}

	const detailMatch = p.match(/^\/api\/mission\/([^/]+)$/);
	if (detailMatch && req.method === "GET") {
		const detail = await getMission(cwd, detailMatch[1]);
		if (!detail) return new Response("Not Found", { status: 404 });
		return jsonResponse(detail);
	}

	const eventsMatch = p.match(/^\/api\/mission\/([^/]+)\/events$/);
	if (eventsMatch && req.method === "GET") {
		const role = url.searchParams.get("role") ?? "worker";
		const events = await getMissionEvents(cwd, eventsMatch[1], role);
		return jsonResponse({ events });
	}

	const streamMatch = p.match(/^\/api\/mission\/([^/]+)\/stream$/);
	if (streamMatch && req.method === "GET") {
		return buildSSEStream(cwd, streamMatch[1]);
	}

	const telemetryMatch = p.match(/^\/api\/mission\/([^/]+)\/telemetry$/);
	if (telemetryMatch && req.method === "GET") {
		const summary = await getMissionTelemetrySummary(cwd, telemetryMatch[1]);
		return jsonResponse(summary ?? {});
	}

	// ── Track J: orch_* surface over HTTP ─────────────────
	// Read-side endpoints parallel the read-side orch_* tools: the same
	// backend handlers are called, so the CLI + web UI can't diverge.

	const contractMatch = p.match(/^\/api\/mission\/([^/]+)\/validation-contract$/);
	if (contractMatch) {
		if (req.method === "GET") {
			const contract = await handleReadValidationContract(cwd);
			return jsonResponse(contract ?? null);
		}
		if (req.method === "POST") {
			const missionId = contractMatch[1] ?? "mission";
			const body = (await req.json().catch(() => null)) as { assertions?: unknown } | null;
			if (!body || !Array.isArray(body.assertions)) {
				return jsonResponse({ ok: false, reason: "invalid_payload" }, { status: 400 });
			}
			try {
				const contract = await handleWriteValidationContract({
					cwd,
					missionId,
					assertions: body.assertions as BehavioralAssertion[],
				});
				return jsonResponse({ ok: true, contract });
			} catch (err) {
				return jsonResponse(
					{ ok: false, reason: err instanceof Error ? err.message : String(err) },
					{ status: 400 },
				);
			}
		}
	}

	const milestonesMatch = p.match(/^\/api\/mission\/([^/]+)\/milestones$/);
	if (milestonesMatch) {
		if (req.method === "GET") {
			const milestones = await handleLoadMilestones(cwd);
			return jsonResponse({ milestones });
		}
		if (req.method === "POST") {
			const body = (await req.json().catch(() => null)) as {
				id?: string;
				name?: string;
				featureIds?: string[];
				assertionIds?: string[];
				maxValidationRounds?: number;
			} | null;
			if (!body || typeof body.id !== "string" || typeof body.name !== "string") {
				return jsonResponse({ ok: false, reason: "invalid_payload" }, { status: 400 });
			}
			try {
				const result = await handleCreateMilestone({
					cwd,
					id: body.id,
					name: body.name,
					featureIds: body.featureIds,
					assertionIds: body.assertionIds,
					maxValidationRounds: body.maxValidationRounds,
				});
				return jsonResponse({ ok: true, ...result });
			} catch (err) {
				return jsonResponse(
					{ ok: false, reason: err instanceof Error ? err.message : String(err) },
					{ status: 400 },
				);
			}
		}
	}

	const statusMatch = p.match(/^\/api\/mission\/([^/]+)\/validation-status$/);
	if (statusMatch && req.method === "GET") {
		const milestoneId = url.searchParams.get("milestoneId") ?? undefined;
		const result = await handleReadValidationStatus(cwd, milestoneId);
		if (!result) return new Response("Not Found", { status: 404 });
		return jsonResponse(result);
	}

	const knowledgeMatch = p.match(/^\/api\/mission\/([^/]+)\/knowledge$/);
	if (knowledgeMatch && req.method === "GET") {
		const entries = await handleKnowledgeEntries(cwd);
		const summaryScope = url.searchParams.get("scope") ?? undefined;
		const limitRaw = url.searchParams.get("limit");
		const limit = limitRaw ? Math.max(1, Math.min(200, Number.parseInt(limitRaw, 10) || 20)) : 20;
		const summary = await handleReadKnowledge(cwd, summaryScope, limit);
		return jsonResponse({ entries, summary });
	}

	const planMatch = p.match(/^\/api\/mission\/([^/]+)\/plan$/);
	if (planMatch) {
		if (req.method === "GET") {
			const manifest = await handleReadPlanManifest(cwd);
			return jsonResponse(manifest ?? null);
		}
	}

	const approveMatch = p.match(/^\/api\/mission\/([^/]+)\/plan\/approve$/);
	if (approveMatch && req.method === "POST") {
		const missionId = approveMatch[1] ?? "mission";
		const body = (await req.json().catch(() => null)) as {
			milestoneIds?: string[];
			featureIds?: string[];
			approvedBy?: string;
		} | null;
		if (!body || !Array.isArray(body.milestoneIds) || !Array.isArray(body.featureIds)) {
			return jsonResponse({ ok: false, reason: "invalid_payload" }, { status: 400 });
		}
		try {
			const manifest = await handleApprovePlan({
				cwd,
				missionId,
				milestoneIds: body.milestoneIds,
				featureIds: body.featureIds,
				approvedBy: body.approvedBy ?? "dashboard",
			});
			return jsonResponse({ ok: true, manifest });
		} catch (err) {
			return jsonResponse({ ok: false, reason: err instanceof Error ? err.message : String(err) }, { status: 400 });
		}
	}

	const rollupMatch = p.match(/^\/api\/mission\/([^/]+)\/telemetry-rollup$/);
	if (rollupMatch && req.method === "GET") {
		const rollup = await handleTelemetryRollup(cwd);
		return jsonResponse(rollup ?? null);
	}

	const rolesMatch = p.match(/^\/api\/mission\/([^/]+)\/role-models$/);
	if (rolesMatch) {
		if (req.method === "GET") {
			return jsonResponse({ roles: await handleReadRoleModels(cwd) });
		}
		if (req.method === "POST") {
			const body = (await req.json().catch(() => null)) as { role?: string; model?: string } | null;
			if (!body || typeof body.role !== "string" || typeof body.model !== "string") {
				return jsonResponse({ ok: false, reason: "invalid_payload" }, { status: 400 });
			}
			try {
				const result = handleSetRoleModel({ cwd, role: body.role, model: body.model });
				return jsonResponse({ ok: true, ...result });
			} catch (err) {
				return jsonResponse(
					{ ok: false, reason: err instanceof Error ? err.message : String(err) },
					{ status: 400 },
				);
			}
		}
	}

	const skillsMatch = p.match(/^\/api\/mission\/([^/]+)\/skills$/);
	if (skillsMatch && req.method === "GET") {
		return jsonResponse(await handleListSkills(cwd));
	}

	const controlMatch = p.match(/^\/api\/mission\/([^/]+)\/(pause|resume|abort)$/);
	if (controlMatch && req.method === "POST") {
		const [, id, action] = controlMatch;
		const body = (await req.json().catch(() => ({}))) as { reason?: string };
		const state = await loadActiveBatch(cwd);
		if (state?.batch && (state.batch.batchId === id || id === "active")) {
			let next = state;
			if (action === "pause") next = pauseBatch(state);
			else if (action === "resume") next = resumeBatch(state);
			else next = abortBatch(state, body.reason ?? "aborted via dashboard");
			await saveActiveBatch(cwd, next);
			return jsonResponse({ ok: true, phase: next.batch?.phase });
		}
		// Simple mission — dispatch to hook so the extension can mutate +
		// persist via saveMissionState / updateWidget.
		const control = getMissionServerHooks().controlSimple;
		if (!control) return new Response("No active mission", { status: 404 });
		const result = control(action as "pause" | "resume" | "abort", { reason: body.reason });
		if (!result.ok) return jsonResponse({ ok: false, reason: result.reason }, { status: 400 });
		return jsonResponse({ ok: true });
	}

	const redirectMatch = p.match(/^\/api\/mission\/([^/]+)\/redirect$/);
	if (redirectMatch && req.method === "POST") {
		const body = (await req.json().catch(() => ({}))) as { message?: string };
		const message = (body.message ?? "").trim();
		if (!message) return jsonResponse({ ok: false, reason: "empty_message" }, { status: 400 });
		const redirect = getMissionServerHooks().redirect;
		if (!redirect) return jsonResponse({ ok: false, reason: "no_hook" }, { status: 503 });
		const result = redirect(message);
		if (!result.ok) return jsonResponse({ ok: false, reason: result.reason }, { status: 400 });
		return jsonResponse({ ok: true });
	}

	const skipPhaseMatch = p.match(/^\/api\/mission\/([^/]+)\/skip-phase$/);
	if (skipPhaseMatch && req.method === "POST") {
		const skip = getMissionServerHooks().skipPhase;
		if (!skip) return jsonResponse({ ok: false, reason: "no_hook" }, { status: 503 });
		const result = skip();
		if (!result.ok) return jsonResponse({ ok: false, reason: result.reason }, { status: 400 });
		return jsonResponse({ ok: true, completedPhaseName: result.completedPhaseName });
	}

	const patchMatch = p.match(/^\/api\/mission\/([^/]+)$/);
	if (patchMatch && req.method === "PATCH") {
		const body = (await req.json().catch(() => null)) as MissionMetaPatch | null;
		if (!body || typeof body !== "object") {
			return jsonResponse({ ok: false, reason: "invalid_payload" }, { status: 400 });
		}
		const patchMission = getMissionServerHooks().patchMission;
		if (!patchMission) return jsonResponse({ ok: false, reason: "no_hook" }, { status: 503 });
		const result = patchMission(body);
		if (!result.ok) return jsonResponse({ ok: false, reason: result.reason }, { status: 400 });
		return jsonResponse({ ok: true });
	}

	// --- /mission-gui: browser → chat dispatch ---------------------------
	if (p === "/api/mission-gui/token" && req.method === "GET") {
		const token = getDefaultToken();
		if (!token) return new Response("Not Found", { status: 404 });
		return jsonResponse({ token, kind: "default" });
	}

	if (p === "/api/mission/start" && req.method === "POST") {
		const body = (await req.json().catch(() => null)) as MissionStartRequest | null;
		if (!body) return jsonResponse({ ok: false, reason: "invalid_payload" }, { status: 400 });
		const result = dispatchStartRequest(body);
		if (!result.ok) {
			const status = result.reason === "unknown_token" ? 403 : 400;
			return jsonResponse({ ok: false, reason: result.reason }, { status });
		}
		return jsonResponse({ ok: true, dispatchedTo: "chat", kind: result.kind }, { status: 202 });
	}

	if (p === "/api/preferences" && req.method === "GET") {
		return jsonResponse(await readDashboardPreferences(cwd));
	}
	if (p === "/api/preferences" && req.method === "POST") {
		const body = (await req.json().catch(() => null)) as Record<string, unknown> | null;
		if (!body || typeof body !== "object") {
			return jsonResponse({ ok: false, reason: "invalid_payload" }, { status: 400 });
		}
		const merged = await writeDashboardPreferences(cwd, body);
		return jsonResponse({ ok: true, preferences: merged });
	}

	// --- History (past batches) ------------------------------------------
	if (p === "/api/history" && req.method === "GET") {
		const entries = await readMissionHistory(cwd);
		return jsonResponse({ entries });
	}

	const historyDetailMatch = p.match(/^\/api\/history\/([^/]+)$/);
	if (historyDetailMatch && req.method === "GET") {
		const entries = await readMissionHistory(cwd);
		const found = entries.find(e => e.batchId === historyDetailMatch[1] || e.missionId === historyDetailMatch[1]);
		if (!found) return new Response("Not Found", { status: 404 });
		return jsonResponse(found);
	}

	// --- Supervisor audit trail ------------------------------------------
	if (p === "/api/supervisor/events" && req.method === "GET") {
		const limit = Number.parseInt(url.searchParams.get("limit") ?? "200", 10);
		const batchId = url.searchParams.get("batchId") ?? undefined;
		try {
			const entries = readAuditTrail(cwd, { limit, batchId });
			return jsonResponse({ eventsPath: supervisorEventsPath(cwd), entries });
		} catch (err) {
			return jsonResponse(
				{ eventsPath: supervisorEventsPath(cwd), entries: [], error: String(err) },
				{ status: 200 },
			);
		}
	}

	// --- Supervisor detail (status + conversation + timeline + summary) -
	if (p === "/api/supervisor/detail" && req.method === "GET") {
		const batchId = url.searchParams.get("batchId") ?? (await activeBatchId(cwd));
		const detail = await getSupervisorDetail(cwd, batchId ?? undefined);
		return jsonResponse(detail);
	}

	// --- Supervisor conversation send (Start-tab chat terminal) ---------
	if (p === "/api/supervisor/send" && req.method === "POST") {
		const body = (await req.json().catch(() => null)) as { content?: string; role?: string } | null;
		const content = typeof body?.content === "string" ? body.content.trim() : "";
		if (!content) return jsonResponse({ ok: false, reason: "empty_message" }, { status: 400 });
		const role = body?.role === "supervisor" ? "supervisor" : "operator";
		await appendSupervisorConversation(cwd, { ts: new Date().toISOString(), role, content });
		return jsonResponse({ ok: true });
	}

	// --- Mailbox events --------------------------------------------------
	if (p === "/api/mailbox/events" && req.method === "GET") {
		const batchId = url.searchParams.get("batchId") ?? (await activeBatchId(cwd));
		if (!batchId) return jsonResponse({ events: [] });
		const limit = Number.parseInt(url.searchParams.get("limit") ?? "200", 10);
		const events = await readMailboxEvents(cwd, batchId, limit);
		return jsonResponse({ batchId, events });
	}

	// --- Agents (process registry snapshot) ------------------------------
	if (p === "/api/agents" && req.method === "GET") {
		const batchId = url.searchParams.get("batchId") ?? (await activeBatchId(cwd));
		if (!batchId) return jsonResponse({ batchId: null, registry: null });
		const registry = readRegistrySnapshot(cwd, batchId);
		return jsonResponse({ batchId, registry });
	}

	// --- Worker conversation transcript ----------------------------------
	const conversationEventsMatch = p.match(/^\/api\/conversation\/([^/]+)\/events$/);
	if (conversationEventsMatch && req.method === "GET") {
		const events = await readLaneConversationEvents(cwd, conversationEventsMatch[1]);
		return jsonResponse({ events });
	}

	const conversationMatch = p.match(/^\/api\/conversation\/([^/]+)$/);
	if (conversationMatch && req.method === "GET") {
		const content = await readLaneConversation(cwd, conversationMatch[1]);
		if (content === null) return new Response("Not Found", { status: 404 });
		return new Response(content, { headers: { "Content-Type": "text/plain; charset=utf-8" } });
	}

	// --- STATUS.md per task ----------------------------------------------
	const statusMdMatch = p.match(/^\/api\/status-md\/([^/]+)$/);
	if (statusMdMatch && req.method === "GET") {
		const content = await readTaskStatusMd(cwd, statusMdMatch[1]);
		if (content === null) return new Response("Not Found", { status: 404 });
		return new Response(content, { headers: { "Content-Type": "text/markdown; charset=utf-8" } });
	}

	const activityMatch = p.match(/^\/api\/mission\/([^/]+)\/activity$/);
	if (activityMatch && req.method === "GET") {
		const entries = await getMissionActivity(cwd, activityMatch[1]);
		return jsonResponse({ entries });
	}

	const agentStatusMatch = p.match(/^\/api\/mission\/([^/]+)\/agent-status$/);
	if (agentStatusMatch && req.method === "GET") {
		const result = await getMissionAgentStatus(cwd, agentStatusMatch[1]);
		return jsonResponse(result);
	}

	const agentEventsMatch = p.match(/^\/api\/agent-events\/([^/]+)$/);
	if (agentEventsMatch && req.method === "GET") {
		return handleAgentEvents(cwd, agentEventsMatch[1], url);
	}

	return new Response("Not Found", { status: 404 });
}

// ---------------------------------------------------------------------------
// Route helpers
// ---------------------------------------------------------------------------

async function activeBatchId(cwd: string): Promise<string | null> {
	const state = await loadActiveBatch(cwd);
	return state?.batch?.batchId ?? null;
}

async function readMissionHistory(
	cwd: string,
): Promise<Array<Record<string, unknown> & { batchId: string; missionId?: string }>> {
	try {
		const raw = await Bun.file(missionHistoryPath(cwd)).text();
		const parsed = JSON.parse(raw) as unknown;
		const arr: unknown[] = Array.isArray(parsed)
			? parsed
			: Array.isArray((parsed as { entries?: unknown[] })?.entries)
				? ((parsed as { entries: unknown[] }).entries ?? [])
				: [];
		return arr.filter(
			(e): e is Record<string, unknown> & { batchId: string } =>
				!!e && typeof e === "object" && typeof (e as { batchId?: unknown }).batchId === "string",
		);
	} catch (err) {
		if (isEnoent(err)) return [];
		logger.warn("[missioncontrol] readMissionHistory failed", {
			error: err instanceof Error ? err.message : String(err),
		});
		return [];
	}
}

async function readMailboxEvents(cwd: string, batchId: string, limit: number): Promise<Array<Record<string, unknown>>> {
	const eventsPath = path.join(mailboxRoot(cwd, batchId), "events.jsonl");
	try {
		const raw = await Bun.file(eventsPath).text();
		const all = Bun.JSONL.parse(raw) as Array<Record<string, unknown>>;
		return limit > 0 ? all.slice(-limit) : all;
	} catch (err) {
		if (!isEnoent(err)) {
			logger.warn("[missioncontrol] readMailboxEvents failed", {
				error: err instanceof Error ? err.message : String(err),
			});
		}
		return [];
	}
}

// Accept either a bare lane id (lane-1) or a batchId:laneId form.
async function readLaneConversation(cwd: string, rawLaneId: string): Promise<string | null> {
	const [maybeBatch, maybeLane] = rawLaneId.includes(":") ? rawLaneId.split(":") : [null, rawLaneId];
	const batchId = maybeBatch ?? (await activeBatchId(cwd));
	if (!batchId) return null;
	const laneSegment = (maybeLane ?? rawLaneId).replace(/[^a-zA-Z0-9._-]/g, "");
	if (!laneSegment) return null;

	const candidates = [
		path.join(missionsDir(cwd), batchId, "lanes", laneSegment, "conversation.md"),
		path.join(missionsDir(cwd), batchId, "lanes", laneSegment, "transcript.md"),
		path.join(missionsDir(cwd), batchId, "lanes", laneSegment, "log.jsonl"),
	];
	for (const candidate of candidates) {
		try {
			return await Bun.file(candidate).text();
		} catch (err) {
			if (!isEnoent(err)) throw err;
		}
	}
	return null;
}

async function readLaneConversationEvents(cwd: string, rawLaneId: string): Promise<Array<Record<string, unknown>>> {
	const [maybeBatch, maybeLane] = rawLaneId.includes(":") ? rawLaneId.split(":") : [null, rawLaneId];
	const batchId = maybeBatch ?? (await activeBatchId(cwd));
	if (!batchId) return [];
	const laneSegment = (maybeLane ?? rawLaneId).replace(/[^a-zA-Z0-9._-]/g, "");
	if (!laneSegment) return [];
	const candidates = [
		path.join(missionsDir(cwd), batchId, "lanes", laneSegment, "conversation.jsonl"),
		path.join(missionsDir(cwd), batchId, "lanes", laneSegment, "log.jsonl"),
	];
	for (const candidate of candidates) {
		try {
			const raw = await Bun.file(candidate).text();
			return Bun.JSONL.parse(raw) as Array<Record<string, unknown>>;
		} catch (err) {
			if (!isEnoent(err)) {
				logger.warn("[missioncontrol] readLaneConversationEvents failed", {
					error: err instanceof Error ? err.message : String(err),
				});
				return [];
			}
		}
	}
	return [];
}

const AGENT_EVENTS_MAX = 300;
const AGENT_ID_PATTERN = /^[\w-]+$/;

async function handleAgentEvents(cwd: string, rawAgentId: string, url: URL): Promise<Response> {
	if (!AGENT_ID_PATTERN.test(rawAgentId)) {
		return jsonResponse({ error: "invalid_agent_id" }, { status: 400 });
	}
	const batchId = await activeBatchId(cwd);
	if (!batchId) return new Response("Not Found", { status: 404 });

	// Path containment — defence in depth against future regex loosening.
	const agentsDir = path.resolve(cwd, ".omp", "runtime", batchId, "agents");
	const agentDir = path.resolve(agentsDir, rawAgentId);
	if (!agentDir.startsWith(agentsDir + path.sep)) {
		return jsonResponse({ error: "forbidden" }, { status: 403 });
	}

	const eventsFile = runtimeAgentEventsPath(cwd, batchId, rawAgentId);
	let events: Array<Record<string, unknown>>;
	try {
		const raw = await Bun.file(eventsFile).text();
		events = Bun.JSONL.parse(raw) as Array<Record<string, unknown>>;
	} catch (err) {
		if (isEnoent(err)) return new Response("Not Found", { status: 404 });
		logger.warn("[missioncontrol] handleAgentEvents failed", {
			error: err instanceof Error ? err.message : String(err),
		});
		return jsonResponse({ events: [] });
	}

	const sinceRaw = url.searchParams.get("sinceTs");
	const sinceTs = sinceRaw ? Number.parseInt(sinceRaw, 10) : 0;
	if (Number.isFinite(sinceTs) && sinceTs > 0) {
		events = events.filter(e => {
			const ts = typeof e.ts === "number" ? e.ts : 0;
			return ts > sinceTs;
		});
	}
	if (events.length > AGENT_EVENTS_MAX) {
		events = events.slice(-AGENT_EVENTS_MAX);
	}
	return jsonResponse({ events });
}

async function readTaskStatusMd(cwd: string, rawTaskId: string): Promise<string | null> {
	const taskId = rawTaskId.replace(/[^a-zA-Z0-9._-]/g, "");
	if (!taskId) return null;
	const base = missionsDir(cwd);
	let dirs: string[] = [];
	try {
		const entries = await fs.readdir(base, { withFileTypes: true });
		dirs = entries.filter(e => e.isDirectory()).map(e => path.join(base, e.name));
	} catch {
		return null;
	}
	for (const dir of dirs) {
		const candidate = path.join(dir, "tasks", taskId, "STATUS.md");
		try {
			return await Bun.file(candidate).text();
		} catch (err) {
			if (!isEnoent(err)) throw err;
		}
	}
	return null;
}

function buildSSEStream(cwd: string, missionId: string): Response {
	const encoder = new TextEncoder();
	let cancelled = false;
	let interval: NodeJS.Timeout | undefined;
	let controllerRef: ReadableStreamDefaultController<Uint8Array> | undefined;

	const stop = (): void => {
		if (cancelled) return;
		cancelled = true;
		if (interval !== undefined) clearInterval(interval);
		if (controllerRef) {
			try {
				controllerRef.close();
			} catch {
				// already closed
			}
		}
	};

	const stream = new ReadableStream<Uint8Array>({
		async start(controller) {
			controllerRef = controller;

			const send = (payload: unknown): void => {
				if (cancelled) return;
				controller.enqueue(encoder.encode(`data: ${JSON.stringify(payload)}\n\n`));
			};

			const tick = async (): Promise<void> => {
				const detail = await getMission(cwd, missionId);
				send({ type: "snapshot", detail });
				// Stop polling once the mission reaches a terminal state.
				if (detail?.state?.completedAt) stop();
			};

			await tick();
			if (cancelled) return;
			interval = setInterval(() => {
				if (cancelled) return;
				void tick();
			}, 2000);
		},
		// Called by the runtime when the consumer (e.g. browser EventSource)
		// disconnects. Must tear down the polling loop to avoid leaking timers.
		cancel() {
			stop();
		},
	});
	return new Response(stream, {
		headers: {
			"Content-Type": "text/event-stream",
			"Cache-Control": "no-cache",
			Connection: "keep-alive",
		},
	});
}

async function handleStatic(requestPath: string): Promise<Response> {
	const staticDir = IS_BUN_COMPILED ? await getCompiledClientDir() : STATIC_DIR;
	const filePath = requestPath === "/" ? "/index.html" : requestPath;
	const fullPath = path.join(staticDir, filePath);

	const file = Bun.file(fullPath);
	if (await file.exists()) return new Response(file);

	const index = Bun.file(path.join(staticDir, "index.html"));
	if (await index.exists()) return new Response(index);

	return placeholderPage();
}

function placeholderPage(): Response {
	const body = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>MissionControl</title></head>
<body style="font-family: system-ui; padding: 40px; max-width: 640px; margin: auto;">
  <h1>MissionControl</h1>
  <p>Dashboard is running but the client bundle has not been built yet.</p>
  <p>Run <code>bun run build</code> inside <code>packages/pi-missions</code> to generate the UI.</p>
  <h2>API</h2>
  <ul>
    <li><a href="/api/missions">/api/missions</a></li>
  </ul>
</body>
</html>`;
	return new Response(body, { headers: { "Content-Type": "text/html" } });
}

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

export interface StartServerOptions {
	port?: number;
	cwd?: string;
}

export async function startServer(options: StartServerOptions = {}): Promise<{ port: number; stop: () => void }> {
	await ensureClientBuild();
	const cwd = options.cwd ?? process.cwd();
	const port = options.port ?? 3848;

	const server = Bun.serve({
		port,
		async fetch(req) {
			const url = new URL(req.url);
			const p = url.pathname;

			const corsHeaders = {
				"Access-Control-Allow-Origin": "*",
				"Access-Control-Allow-Methods": "GET, POST, OPTIONS",
				"Access-Control-Allow-Headers": "Content-Type",
			};

			if (req.method === "OPTIONS") {
				return new Response(null, { headers: corsHeaders });
			}

			try {
				const response = p.startsWith("/api/") ? await handleApi(req, cwd) : await handleStatic(p);

				const headers = new Headers(response.headers);
				for (const [k, v] of Object.entries(corsHeaders)) headers.set(k, v);
				return new Response(response.body, { status: response.status, headers });
			} catch (error) {
				logger.error("[missioncontrol] server request failed", {
					error: error instanceof Error ? error.message : String(error),
				});
				return jsonResponse(
					{ error: error instanceof Error ? error.message : "Unknown error" },
					{ status: 500, headers: corsHeaders },
				);
			}
		},
	});

	return {
		port: server.port ?? port,
		stop: () => server.stop(),
	};
}
